### PR TITLE
added JavaScript questions

### PR DESCRIPTION
**Pull request by pramod74**
### Pull Request Checklist

- [ ] You are submitting a maximum of three flashcards.
- [ ] You have verified that the information is correct, via a book, ChatGPT etc.
- [ ] You are using correct grammar and spelling.
- [ ] You are using bullet answer format and the question dictates how many bullets are in the answer.
- [ ] You are using the below pattern to add the flashcard:

      
      
      ###### Question number.
      
      Question goes here
      
      <details><summary><b>Answer</b></summary>
      <p>
      
      Answer goes here
      
      </p>
      </details>
      
      <br><br>

### CODE REVIEW

**Review by calwoodford — CHANGES_REQUESTED** [review]
Arrow function question already exists in the deck (q39) - please remove or change this question.

**Comment by pramod74** [comment]
Sorry about that. I have removed the question on arrow functions. Kindly review again.

**Comment by pramod74** [comment]
Sorry, closed the PR by mistake. Still learning to use Git and GitHub also.

**Review by calwoodford — APPROVED** [review]
Thank you!

**Pull request merged**
